erupt-app:
  # 登录失败几次，需要验证码
  verifyCodeCount: 2
erupt:
  # 是否开启csrf防御
  csrfInspect: true
  # 是否开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 spring boot）
  redisSession: false
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  uploadPath: D:/erupt/attachment
  # 是否保留上传文件原始名称
  keepUploadFileName: false
  # 登录session时长（redisSession为true时有效）
  upms.expireTimeByLogin: 60
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security.recordOperateLog: true

magic-api:
  web: /magic/web
  # 接口配置文件存放路径
  resource.location: D:/erupt/magic-script
  show-url: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: qwxy74152077
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  profiles:
    active: dev
  mail:
    username: xxxx@qq.com
    password: xxxxxxx
    host: smtp.qq.com
    properties:
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  # 启用 gzip 压缩
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS


#  # Redis数据库索引（默认为0）
#  spring.redis.database: 0
#  # Redis服务器地址
#  spring.redis.host: 10.1.30.222
#  # Redis服务器连接端口
#  spring.redis.port: 6379
#  # Redis服务器连接密码（默认为空）
#  #spring.redis.password=123456
#  # 连接池最大连接数（使用负值表示没有限制） 默认 8
#  spring.redis.lettuce.pool.max-active: 8
#  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#  spring.redis.lettuce.pool.max-wait: -1
#  # 连接池中的最大空闲连接 默认 8
#  spring.redis.lettuce.pool.max-idle: 8
#  # 连接池中的最小空闲连接 默认 0
#  spring.redis.lettuce.pool.min-idle: 0
#  ## 连接超时时间（毫秒）
#  spring.redis.timeout: 30000